### ISSUE TITLE
Freeze on module load (4.11)

### ISSUE THREAD

**Issue by Miouyouyou** [Miouyouyou/rockchip-vcodec#2]
When loading the module the system freezes instantly. **KGDB** is unable to react and is, therefore, useless to debug this issue.

After various reboot, following the code flow and putting `return 0` at different places, it looks like the issue is located inside the `vpu_service_check_hw` function.

**Comment by Miouyouyou** [comment]
The function in question:

https://github.com/Miouyouyou/rockchip-vcodec/blob/master/vcodec_service.c#L2037

**Comment by Miouyouyou** [comment]
Alright ! The freeze happens here:

https://github.com/Miouyouyou/rockchip-vcodec/blob/master/vcodec_service.c#L2042

Now, I'll have to look for the reasons...

**Comment by hizukiayaka** [comment]
It looks like the VPU is not power on

**Comment by Miouyouyou** [comment]
Ah ! Is there a way to check this before loading the module ?

**Comment by hizukiayaka** [comment]
The default code should make it power on
https://github.com/Miouyouyou/rockchip-vcodec/blob/master/vcodec_service.c#L2346

**Comment by Miouyouyou** [comment]
Alright, I'll check that this evening. I'll try to see if something goes wrong during the power-on phase.

**Comment by Miouyouyou** [comment]
Problem resolved. [Your patch](https://github.com/Miouyouyou/MyyQi/blob/e309cc03ae324b03d22b4d5f261987e7d5a156cc/patches/kernel/v4.11/0013-clk-rockchip-rk3288-prefer-vdpu-for-vcodec-clock-sou.patch) did the trick :+1: 

The patch in question

https://github.com/Miouyouyou/MyyQi/blob/e309cc03ae324b03d22b4d5f261987e7d5a156cc/patches/kernel/v4.11/0013-clk-rockchip-rk3288-prefer-vdpu-for-vcodec-clock-sou.patch
